name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies and package
        run: |
          mkdir -p package
          pip install -r requirements.txt -t package/
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .
          cd ..
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name myFirstLambdaFunction \
            --zip-file fileb://lambda_function.zip \
            --publish
